@Test._AutotestesEcosystemAPI_HostAddress = http://localhost:5172

GET {{Test._AutotestesEcosystemAPI_HostAddress}}/todos/
Accept: application/json

###

GET {{Test._AutotestesEcosystemAPI_HostAddress}}/todos/1
Accept: application/json

###
