version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: autotestes-api
    ports:
      - "8000:8000"
    volumes:
      - ./main.py:/app/main.py
    restart: unless-stopped

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: autotestes-swagger
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/app/swagger.json
      - URLS=[{"name":"Autotestes API","url":"http://fastapi-app:8000/openapi.json"}]
    depends_on:
      - fastapi-app
    restart: unless-stopped